# Generated by Django 4.2.5 on 2023-09-20 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Carrot",
            new_name="Carro",
        ),
    ]
